package com.Yu.Pan.service.domain;

import java.util.Date;

/**
 * 物理文件表（表：file）
 *
 * @author heyu
 * @date 2024-06-29 20:00:33
 */
public class File {
    /**
     * 文件id
     */
    private Long id;

    /**
     * 文件名称
     */
    private String fileName;

    /**
     * 文件物理路径
     */
    private String realPath;

    /**
     * 文件实际大小
     */
    private String fileSize;

    /**
     * 文件大小展示字符
     */
    private String fileSizeDesc;

    /**
     * 文件后缀
     */
    private String fileSuffix;

    /**
     * 文件预览的响应头Content-Type的值
     */
    private String filePreviewContentType;

    /**
     * 文件唯一标识
     */
    private String identifier;

    /**
     * 创建人
     */
    private Long createUser;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.id
     *
     * @return the value of file.id
     *
     * @mbg.generated Sat Jun 29 20:00:33 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.id
     *
     * @param id the value for file.id
     *
     * @mbg.generated Sat Jun 29 20:00:33 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_name
     *
     * @return the value of file.file_name
     *
     * @mbg.generated Sat Jun 29 20:00:33 CST 2024
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_name
     *
     * @param fileName the value for file.file_name
     *
     * @mbg.generated Sat Jun 29 20:00:33 CST 2024
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.real_path
     *
     * @return the value of file.real_path
     *
     * @mbg.generated Sat Jun 29 20:00:33 CST 2024
     */
    public String getRealPath() {
        return realPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.real_path
     *
     * @param realPath the value for file.real_path
     *
     * @mbg.generated Sat Jun 29 20:00:33 CST 2024
     */
    public void setRealPath(String realPath) {
        this.realPath = realPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_size
     *
     * @return the value of file.file_size
     *
     * @mbg.generated Sat Jun 29 20:00:33 CST 2024
     */
    public String getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_size
     *
     * @param fileSize the value for file.file_size
     *
     * @mbg.generated Sat Jun 29 20:00:33 CST 2024
     */
    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_size_desc
     *
     * @return the value of file.file_size_desc
     *
     * @mbg.generated Sat Jun 29 20:00:33 CST 2024
     */
    public String getFileSizeDesc() {
        return fileSizeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_size_desc
     *
     * @param fileSizeDesc the value for file.file_size_desc
     *
     * @mbg.generated Sat Jun 29 20:00:33 CST 2024
     */
    public void setFileSizeDesc(String fileSizeDesc) {
        this.fileSizeDesc = fileSizeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_suffix
     *
     * @return the value of file.file_suffix
     *
     * @mbg.generated Sat Jun 29 20:00:33 CST 2024
     */
    public String getFileSuffix() {
        return fileSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_suffix
     *
     * @param fileSuffix the value for file.file_suffix
     *
     * @mbg.generated Sat Jun 29 20:00:33 CST 2024
     */
    public void setFileSuffix(String fileSuffix) {
        this.fileSuffix = fileSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_preview_content_type
     *
     * @return the value of file.file_preview_content_type
     *
     * @mbg.generated Sat Jun 29 20:00:33 CST 2024
     */
    public String getFilePreviewContentType() {
        return filePreviewContentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_preview_content_type
     *
     * @param filePreviewContentType the value for file.file_preview_content_type
     *
     * @mbg.generated Sat Jun 29 20:00:33 CST 2024
     */
    public void setFilePreviewContentType(String filePreviewContentType) {
        this.filePreviewContentType = filePreviewContentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.identifier
     *
     * @return the value of file.identifier
     *
     * @mbg.generated Sat Jun 29 20:00:33 CST 2024
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.identifier
     *
     * @param identifier the value for file.identifier
     *
     * @mbg.generated Sat Jun 29 20:00:33 CST 2024
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.create_user
     *
     * @return the value of file.create_user
     *
     * @mbg.generated Sat Jun 29 20:00:33 CST 2024
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.create_user
     *
     * @param createUser the value for file.create_user
     *
     * @mbg.generated Sat Jun 29 20:00:33 CST 2024
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.create_time
     *
     * @return the value of file.create_time
     *
     * @mbg.generated Sat Jun 29 20:00:33 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.create_time
     *
     * @param createTime the value for file.create_time
     *
     * @mbg.generated Sat Jun 29 20:00:33 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public void initDefault() {
    }

    public void initUpdate() {
    }
}