package com.Yu.Pan.service.domain;

import java.util.Date;

/**
 * 用户文件信息表（表：user_file）
 *
 * @author heyu
 * @date 2024-06-29 21:06:54
 */
public class UserFile {
    /**
     * 文件记录id
     */
    private Long fileId;

    /**
     * 用户id
     */
    private Long userId;

    /**
     * 上级文件夹id,,顶级文件夹为0
     */
    private Long parentId;

    /**
     * 真实文件id
     */
    private Long realFileId;

    /**
     * 文件名
     */
    private String filename;

    /**
     * 是否是文件夹(0 否 1 是)
     */
    private Boolean folderFlag;

    /**
     * 1 普通文件 2 压缩文件 3 excel 4 word 5 pdf 6 txt 7 图片 8 音频 9 视频 10 ppt 11 源码文件 12 csv
     */
    private String fileType;

    /**
     * 文件大小展示符
     */
    private String fileSizeDesc;

    /**
     * 删除标识
     */
    private Boolean delFlag;

    /**
     * 创建人
     */
    private Long createUser;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 更新人
     */
    private Long updateUser;

    /**
     * 更新时间
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.file_id
     *
     * @return the value of user_file.file_id
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public Long getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.file_id
     *
     * @param fileId the value for user_file.file_id
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.user_id
     *
     * @return the value of user_file.user_id
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.user_id
     *
     * @param userId the value for user_file.user_id
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.parent_id
     *
     * @return the value of user_file.parent_id
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.parent_id
     *
     * @param parentId the value for user_file.parent_id
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.real_file_id
     *
     * @return the value of user_file.real_file_id
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public Long getRealFileId() {
        return realFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.real_file_id
     *
     * @param realFileId the value for user_file.real_file_id
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public void setRealFileId(Long realFileId) {
        this.realFileId = realFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.filename
     *
     * @return the value of user_file.filename
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.filename
     *
     * @param filename the value for user_file.filename
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.folder_flag
     *
     * @return the value of user_file.folder_flag
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public Boolean getFolderFlag() {
        return folderFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.folder_flag
     *
     * @param folderFlag the value for user_file.folder_flag
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public void setFolderFlag(Boolean folderFlag) {
        this.folderFlag = folderFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.file_type
     *
     * @return the value of user_file.file_type
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.file_type
     *
     * @param fileType the value for user_file.file_type
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.file_size_desc
     *
     * @return the value of user_file.file_size_desc
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public String getFileSizeDesc() {
        return fileSizeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.file_size_desc
     *
     * @param fileSizeDesc the value for user_file.file_size_desc
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public void setFileSizeDesc(String fileSizeDesc) {
        this.fileSizeDesc = fileSizeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.del_flag
     *
     * @return the value of user_file.del_flag
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.del_flag
     *
     * @param delFlag the value for user_file.del_flag
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.create_user
     *
     * @return the value of user_file.create_user
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.create_user
     *
     * @param createUser the value for user_file.create_user
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.create_time
     *
     * @return the value of user_file.create_time
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.create_time
     *
     * @param createTime the value for user_file.create_time
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.update_user
     *
     * @return the value of user_file.update_user
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.update_user
     *
     * @param updateUser the value for user_file.update_user
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.update_time
     *
     * @return the value of user_file.update_time
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.update_time
     *
     * @param updateTime the value for user_file.update_time
     *
     * @mbg.generated Sat Jun 29 21:06:54 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public void initDefault() {
        if (this.getCreateTime() == null) {
            this.setCreateTime(new Date());
        }
    }

    public void initUpdate() {
    }
}